# https://www.netlifycms.org/docs/configuration-options/#display-url
display_url: https://sojustrepairit.org/

backend:
  name: github
  repo: fluid-project/sojustrepairit.org

# https://www.netlifycms.org/docs/configuration-options/#media-and-public-folders
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

# https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: "landing"
    label: "Landing"
    folder: "content/"
    create: false
    identifier_field: title
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "type", name: "type", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "about"
    label: "About"
    folder: "content/about/"
    create: false
    identifier_field: title
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "type", name: "type", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "partners"
    label: "Partners"
    folder: "content/partners/"
    create: false
    identifier_field: title
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "projectUrl", name: "projectUrl", widget: "string", default: "http://sojustrepairit.org"}
      - {label: "summary", name: "summary", widget: "string", default: "  "}
      - {label: "aboutPartner", name: "aboutPartner", widget: "string", default: "  "}
      - {label: "imgURL", name: "imgURL", widget: "string"}
      - {label: "imgAlt", name: "imgAlt", widget: "string"}
      - {label: "imgCap", name: "imgCap", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "resources"
    label: "Resources"
    folder: "content/resources/"
    create: false
    identifier_field: title
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "type", name: "type", widget: "string"}
      - {label: "weight", name: "type", widget: "number"}
      - {label: "imgURL", name: "imgURL", widget: "string"}
      - {label: "imgAlt", name: "imgAlt", widget: "string"}
      - {label: "imgCap", name: "imgCap", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
